# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='gender',
            field=models.CharField(default='NaN', max_length=10),
            preserve_default=False,
        ),
    ]
